VENV_PATH=~/venv
APP_MODULE=app:app

.PHONY: run stop restart

run:
	@echo "Starting uWSGI with elevated privileges..."
	@sudo uwsgi --plugin python \
	       --home $(VENV_PATH) \
	       --socket 127.0.0.1:9090 \
	       --module $(APP_MODULE) \
	       --daemonize uwsgi.log
	@sleep 2
	@echo "Restarting Nginx..."
	@sudo systemctl restart nginx
	@echo "App is running at http://127.0.0.1"

stop:
	@echo "Stopping uWSGI..."
	@sudo killall -q uwsgi || true

restart: stop
	@sleep 1
	@$(MAKE) run
